const actions = {
  GET_USERS: 'GET_USERS',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
  GET_USER_POSTS: 'GET_USER_POSTS',
  GET_USER_POSTS_SUCCESS:'GET_USER_POSTS_SUCCESS',
  GET_USER_POSTS_FAILURE: 'GET_USER_POSTS_FAILURE',
  GET_USER_POST_DETAILS: 'GET_USER_POST_DETAILS',
  GET_USER_POST_DETAILS_SUCCESS: 'GET_USER_POST_DETAILS_SUCCESS',
  GET_USER_POST_DETAILS_FAILURE: 'GET_USER_POST_DETAILS_FAILURE',
  SET_POST_DETAILS: 'SET_POST_DETAILS',
  SHOW_COMMENT_MODAL: 'SHOW_COMMENT_MODAL',
  ADD_COMMENT: 'ADD_COMMENT',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',
  ADD_POST: 'ADD_POST',
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
  ADD_POST_FAILURE: 'ADD_POST_FAILURE',
};

export default actions;
